services:
  stakewise:
    image: "europe-west4-docker.pkg.dev/stakewiselabs/public/v3-operator:master"
    container_name: v3-operator
    command: src/main.py start
      --vault=$VAULT
      --consensus-endpoints="$CCURL:$CCAPIPORT"
      --execution-endpoints="$ECURL:$ECAPIPORT"
    volumes:
      - "$DATA_DIR/stakewise-data:/data"
    environment:
      DATA_DIR: /data
    env_file: "$DATA_DIR/nodeset.env"
    networks:
      - hyperdrive-stakewise
  ethdo:
    image: "wealdtech/ethdo"
    env_file: "$DATA_DIR/nodeset.env"
    networks:
      - hyperdrive-stakewise

networks:
  hyperdrive-stakewise:
    name: $DOCKER_NETWORK
    external: $IS_EXTERNAL_DOCKER_NETWORK