services:
  nethermind:
    image: "nethermind/nethermind:latest"
    command: -c $NETWORK
      -dd "/root/.$ECNAME"
      --Pruning.Mode=Hybrid 
      --Pruning.FullPruningTrigger=VolumeFreeSpace
      --Network.DiscoveryPort=$ECPORT
      --Network.P2PPort=$ECPORT
      --JsonRpc.EngineHost="0.0.0.0"
      --JsonRpc.EnginePort=$ECRPCPORT
      --JsonRpc.Enabled=true
      --JsonRpc.Host="0.0.0.0"
      --JsonRpc.Port=$ECAPIPORT
      --JsonRpc.JwtSecretFile=/jwtsecret/jwtsecret
    env_file: "$DATA_DIR/nodeset.env"
    volumes:
      - "$DATA_DIR/jwtsecret:/jwtsecret"
      - "$DATA_DIR/$ECNAME-data:/root/.$ECNAME"
    ports:
      # external peering
      - "$ECPORT/tcp"
      - "$ECPORT/udp"
      # connection to CC
      - "$ECRPCPORT/tcp"
      - "$ECRPCPORT/udp"
      # http API
      - "$ECAPIPORT/tcp"
      - "$ECAPIPORT/udp"